project_name: melange

before:
  hooks:
    - go mod download
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

env:
  - COSIGN_YES=true

builds:
- id: melange-build
  binary: melange
  main: ./
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - "386"
    - amd64
    - arm64
  ignore:
    - goos: darwin
      goarch: "386"
  flags:
    - -trimpath
  mod_timestamp: '{{ .CommitTimestamp }}'
  ldflags:
    - -extldflags "-static"
    - "{{ .Env.LDFLAGS }}"

signs:
  - id: melange-cosign
    cmd: cosign
    certificate: "${artifact}.crt"
    args: ["sign-blob", "--output-signature", "${signature}", "--output-certificate", "${certificate}", "${artifact}", "--yes"]
    artifacts: all

archives:
  - files:
      - LICENSE
    wrap_in_directory: true
    rlcp: true

brews:
  - name: melange
    tap:
      owner: chainguard-dev
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/chainguard-dev/melange/releases/download/{{ .Version }}/{{ .ArtifactName }}"
    folder: Formula
    commit_author:
      name: guardian
      email: guardian@chainguard.dev
    homepage: "https://github.com/chainguard-dev/melange"
    description: "Build apk packages using declarative pipelines"
    install: |
      bin.install "{{ .Binary }}" => "{{ .ProjectName }}"
    test: |
      system "#{bin}/{{ .ProjectName }}", "version"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto
  name_template: "Release {{ .Tag }}"
