package:
  name: melange
  version: 0.0.1
  epoch: 0
  description: "a cloud-native packaging build system"
  copyright:
    - attestation: |
        Copyright 2022 Chainguard, Inc.
      license: Apache-2.0
  dependencies:
    runtime:
      - bubblewrap

environment:
  contents:
    repositories:
      - https://apk.cgr.dev/chainguard
    packages:
      - wolfi-baselayout
      - busybox
      - make
      - go
      - git
      - ca-certificates-bundle

pipeline:
  - uses: autoconf/make-install
