# test that packages / subpackages build and test as root when
# specified in the build configuration
package:
  name: accounts-root-build-test
  description: Test that specifying non-root builds happen as non-root
  version: 0.1.0
  epoch: 0
environment:
  contents:
    packages:
      - busybox
  accounts:
    # build environments should have the root user (uid=0) created by default
    run-as: root
pipeline:
  - uses: check-accounts
    with:
      expected_uid: 0
      expected_username: root
      expected_gid: 0
      expected_groupname: root
subpackages:
  - name: accounts-root-build-subpackage-test
    description: test that when specifying root at the top-level, subpackage builds also happen as root
    pipeline:
      - uses: check-accounts
        with:
          expected_uid: 0
          expected_username: root
          expected_gid: 0
          expected_groupname: root
    test:
      environment:
        contents:
          packages:
            - busybox
        accounts:
          # test environments should have the root user (uid=0) created by default
          run-as: root
      pipeline:
        - uses: check-accounts
          with:
            expected_uid: 0
            expected_username: root
            expected_gid: 0
            expected_groupname: root
  - name: accounts-root-build-subpackage-build-user-test
    description: test that when specifying root at the top-level, subpackage tests can be performed as build user
    # Note: melange does not seem to support specifying a different user in
    # a subpackage build, so don't do anything in this subpackage's
    # build phase
    test:
      environment:
        contents:
          packages:
            - busybox
        accounts:
          # test environments should have the build user (uid=1000) created by default
          run-as: build
      pipeline:
        - uses: check-accounts
          with:
            expected_uid: 1000
            expected_username: build
            expected_gid: 1000
            expected_groupname: build
  - name: accounts-root-build-subpackage-nonstd-user-test
    description: test that when specifying root at the top-level, subpackage tests can be performed as non-std unprivileged user
    test:
      environment:
        contents:
          packages:
            - busybox
        accounts:
          run-as: nonroot
          users:
            - username: nonroot
              uid: 12345
              gid: 12346
          groups:
            - groupname: nongroup
              gid: 12346
      pipeline:
        - uses: check-accounts
          with:
            expected_uid: 12345
            expected_username: nonroot
            expected_gid: 12346
            expected_groupname: nongroup
test:
  environment:
    contents:
      packages:
        - busybox
    accounts:
      # test environments should have the root user (uid=0) created by default
      run-as: root
  pipeline:
    - uses: check-accounts
      with:
        expected_uid: 0
        expected_username: root
        expected_gid: 0
        expected_groupname: root
