package:
  name: numpy
  version: 2.1.3
  epoch: 1
  description: Tests for py3-pandas using python test pipelines

pipeline:

# Test python/import, and python/test pipelines
test:
  environment:
    # TODO(pnasrat): fix to use multiple python
    contents:
      packages:
        - python-3.12
  pipeline:
    # Test import with command (python -c "import numpy")
    - uses: python/test
      with:
        command: python3.12 -c "import numpy"
    # Test import directly (python -c "import numpy")
    - uses: python/import
      with:
        import: numpy
    # Test import directly (python -c "import numpy.ma")
    - uses: python/import
      with:
        import: numpy.ma
    # Test import with from clause (python -c "from numpy import ma")
    - uses: python/import
      with:
        import: ma
        from: numpy
