# E2E test for retry pipeline functionality
# This test verifies that:
# 1. Retry configuration is properly parsed and compiled
# 2. Pipelines with retry fail and then succeed after retries
# 3. Pipelines without retry work as normal (backward compatibility)
# 4. Retry logging is correct

package:
  name: retry-test
  version: 1.0.0
  epoch: 0
  description: E2E test for pipeline retry functionality
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

pipeline:
  # Test 1: Pipeline with retry that fails first then succeeds
  - name: test-retry-mechanism
    retry:
      attempts: 5
      backoff: constant
      initial-delay: 200ms
    runs: |
      echo "Testing retry mechanism..."

      # Use a counter file in workspace to track attempts
      COUNTER_FILE="$HOME/.retry_test_counter"

      if [ ! -f "$COUNTER_FILE" ]; then
        echo "1" > "$COUNTER_FILE"
        echo "First attempt - intentionally failing"
        exit 1
      fi

      COUNTER=$(cat "$COUNTER_FILE")
      COUNTER=$((COUNTER + 1))
      echo "$COUNTER" > "$COUNTER_FILE"

      echo "Attempt number: $COUNTER"

      # Fail on first 2 attempts, succeed on 3rd
      if [ "$COUNTER" -lt 3 ]; then
        echo "Failing on attempt $COUNTER"
        exit 1
      fi

      echo "SUCCESS on attempt $COUNTER!"
      echo "Retry mechanism working correctly"

  # Test 2: Pipeline with retry that succeeds immediately (no actual retries)
  - name: test-immediate-success
    retry:
      attempts: 3
      backoff: exponential
    runs: |
      echo "Testing immediate success with retry config..."
      echo "This should succeed on first attempt"
      echo "No retries should occur"

  # Test 3: Pipeline without retry (backward compatibility)
  - name: test-no-retry
    runs: |
      echo "Testing backward compatibility..."
      echo "This pipeline has no retry configuration"
      echo "Should run exactly once as before"

  # Test 4: Create a test file that the test phase can verify
  - name: create-test-marker
    runs: |
      mkdir -p ${{targets.destdir}}/usr/share/retry-test
      echo "Retry tests completed successfully" > ${{targets.destdir}}/usr/share/retry-test/marker.txt
      chmod 644 ${{targets.destdir}}/usr/share/retry-test/marker.txt

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - name: verify-retry-functionality
      runs: |
        echo "Verifying retry functionality in test phase..."

        # Verify the marker file exists (proves build succeeded with retries)
        if [ ! -f /usr/share/retry-test/marker.txt ]; then
          echo "FAIL: Marker file not found"
          exit 1
        fi

        content=$(cat /usr/share/retry-test/marker.txt)
        if [ "$content" != "Retry tests completed successfully" ]; then
          echo "FAIL: Marker content incorrect"
          exit 1
        fi

        echo "PASS: Retry functionality verified"
        echo "All retry tests completed successfully"
