#!/bin/sh
vrc() {
    local name="$1" rc=""
    shift
    echo "$name"
    echo "execute: $*"
    "$@"
    rc=$?
    [ $rc -eq 0 ] || echo "ERROR[$rc]: $name"
    return $rc
}

ARCH=${ARCH:-$(uname -m)}
# macOS reports "arm64"
if [ "arm64" = "${ARCH}" ]; then
    ARCH="aarch64"
fi

MELANGE=${MELANGE:-melange}
if [ "$MELANGE" = "melange" ]; then
    MELANGE=$(which melange)
fi
ARGS=${ARGS:-""}

echo "Testing with melange from $MELANGE"
$MELANGE version --json

if [ $# -eq 0 ]; then
    set -- *.yaml
fi

key="local-melange.rsa"
if [ -f "$key" -a -f "$key.pub" ]; then
    echo "using existing $key"
else
    $MELANGE keygen "$key" ||
        { echo "failed to create local-melange signing key"; exit 1; }
fi

fails=""
for yaml in "$@"; do
  args="${ARGS}"
  ops=""
  arch_flag="${ARCH}"
  multiarch=""
  base=${yaml%.yaml}
  case "$base" in
    *-build-test)
      ops="build test"
      args="$args --debug"
      ;;
    *-nopkg-test)
      ops="test"
      args="$args --test-package-append busybox"
      args="$args --test-package-append=python-3"
      args="$args --debug"
      ;;
    *-test)
      ops="test"
      args="${base%-test}"
      args="$args --debug"
      ;;
    *-multiarch-build)
      ops="build"
      arch_flag="x86_64,aarch64"
      multiarch="true"
      ;;
    *-build)
      ops="build"
      ;;
    *)
      echo "ERROR: Unexpected input '$yaml'."
      exit 1
      ;;
  esac

  for op in $ops; do
    opargs=""
    case "$op" in
        # For some reason build takes '--pipeline-dir' and test takes
        # --pipeline-dirs. And we need to pass both to compile the
        # melange file
        "build") opargs="--signing-key=$PWD/$key --pipeline-dir $PWD/pipelines";;
        "test") opargs="--pipeline-dirs $PWD/pipelines";;
    esac

    if vrc "Testing $base from $yaml for $op" \
      ${MELANGE} "$op" \
        --arch=${arch_flag} --source-dir=./test-fixtures \
        --runner=qemu \
        "$yaml" \
        ${args} $opargs \
        "--keyring-append=$PWD/$key.pub" \
        "--repository-append=$PWD/packages" \
        "--repository-append=https://packages.wolfi.dev/os" \
        "--keyring-append=https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"; then
      if [ -n "$multiarch" ]; then
        for arch in x86_64 aarch64; do
          apk="packages/$arch/noarch-multiarch-test-1.0-r0.apk"
          index="packages/$arch/APKINDEX.tar.gz"
          if [ ! -f "$apk" ]; then
            echo "ERROR: missing noarch package $apk"
            fails="${fails} $yaml/$op"
          fi
          if [ ! -f "$index" ]; then
            echo "ERROR: missing package index $index"
            fails="${fails} $yaml/$op"
          fi
        done
      fi
    else
      fails="${fails} $yaml/$op"
    fi
  done
done

if [ -z "$fails" ]; then
    echo "PASS: $*"
    exit 0
fi
echo "FAIL: $fails"
exit 1
