package:
  name: symlinks-in-workspace-build
  description: Test that symlinks are copied into workspaces
  version: 0.1.0
  epoch: 0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - name: Test for symlink presence in workspace
    runs: |
      testdata_linked=$(cat testdata-symlink.txt)
      testdata=$(cat testdata.txt)
      [ "$testdata" = "$testdata_linked" ]
