package:
  name: gitlab-exporter
  version: 13.4.1
  epoch: 0
  description: GitLab Exporter is a Prometheus Web exporter.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - jemalloc
      - ruby-3.2
      - libpq-15
      - busybox
      - ruby3.2-webrick
      - ruby3.2-faraday
      - ruby3.2-faraday-excon
      - ruby3.2-rack
      - ruby3.2-bundler
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - bash
      - build-base
      - busybox
      - libpq-15
      - postgresql-15-dev
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler
vars:
  gem: gitlab-exporter
pipeline:
  # GitLab-Exporter
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/ruby/gems/gitlab-exporter.git
      tag: v${{package.version}}
      expected-commit: 590c4261bd09b341742ee5249225b3aaac421445
  # GitLab-Exporter Runtime Dependencies
  - uses: ruby/install_runtime_deps
    with:
      gem: ${{vars.gem}}
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
