package:
  name: hello
  version: 2.12
  epoch: 0
  description: "an example of how conditionals influence build behavior"
  copyright:
    - license: Not-Applicable
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox

pipeline:
  # at least one of the steps in the sub-pipeline below
  # must run for the build to pass
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'x86_64'
        runs: |
          echo "build arch is x86_64!"
      - if: ${{build.arch}} == 'aarch64'
        runs: |
          echo "build arch is aarch64!"

  # this should print "package name matches 'hello'!"
  - if: ${{package.name}} == 'hello'
    runs: |
      echo "package name matches 'hello'!"

  # this shouldn't print anything.
  - if: ${{package.name}} != 'hello'
    runs: |
      echo "package name doesn't match hello!"

  # likewise, this shouldn't fetch
  - uses: fetch
    if: ${{package.name}} != 'hello'
    with:
      uri: https://mirrors.ocf.berkeley.edu/gnu/hello/hello-${{package.version}}.tar.gz
      expected-sha256: cf04af86dc085268c5f4470fbae49b18afbc221b78096aab842d934a76bad0ab

  - runs: |
      mkdir -p "${{targets.destdir}}"
