package:
  name: hello
  version: 2.12
  epoch: 0
  description: "an example of how conditionals influence build behavior"
  copyright:
    - license: Not-Applicable
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox

pipeline:
  # at least one of the steps in the sub-pipeline below
  # must run for the build to pass
  - if-arch: 'x86_64'
    runs: |
      echo "build arch is x86_64!"
  - if-arch: 'aarch64'
    runs: |
      echo "build arch is aarch64!"

  - runs: |
      mkdir -p "${{targets.destdir}}"
