package:
  name: fetch-directory
  version: 0.0.1
  epoch: 0
  description: "an example of how to use the directory option in the fetch pipeline"
  copyright:
    - license: Not-Applicable

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox

pipeline:
  - uses: fetch
    with:
      uri: https://unofficial-builds.nodejs.org/download/release/v22.9.0/node-v22.9.0-linux-x64-glibc-217.tar.gz
      directory: /home/node/
      delete: false

  - runs: ls /home/node/*.tar.gz
