package:
  name: if-arch
  version: 0.0.1
  epoch: 0
  description: "an example of how if-arch works"
  copyright:
    - license: Not-Applicable

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox

pipeline:
  - if-arch: x86_64
    runs: |
      echo "build arch is x86_64!"

  - if-arch: aarch64
    runs: |
      echo "build arch is aarch64!"

  - if-arch: amd64
    runs: |
      echo "OCI-style arch name for x86_64!"

  - if-arch: arm64
    runs: |
      echo "OCI-style arch name for aarch64!"

  # This shouldn't run, since the arch isn't valid
  - if-arch: bad-architecture-name
    runs: |
      echo "BAD ARCHITECTURE"
      exit 1
