package:
  name: minimal
  version: 0.0.1
  epoch: 0
  description: a very basic melange example

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox

pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}"
      echo "hello" > "${{targets.destdir}}/hello"

data:
  - name: lagomorphs
    items:
      hare: 'lepus saxatilis'
      rabbit: 'sylvìlagus floridanus'
      pika: 'ochotona princeps'

subpackages:
  - range: lagomorphs
    name: "lagomorph-${{range.key}}"
    description: "data about the lagomorph ${{range.value}}"
    pipeline:
      - runs: |
          echo "${{range.value}}" > ${{targets.contextdir}}/${{range.key}}
