package:
  name: minimal
  version: 0.0.1
  description: a very basic melange example
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}"
      echo "hello" > "${{targets.destdir}}/hello"
