issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/melange:ref:refs/heads/main
claim_pattern:
  workflow_ref: chainguard-dev/melange/.github/workflows/digestabot.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
