name: Go Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            7-zip.org:443
            api.github.com:443
            azure.archive.ubuntu.com:80
            dl.google.com:443
            esm.ubuntu.com:443
            files.pythonhosted.org:443
            git.savannah.gnu.org:443
            git.sv.gnu.org:443
            git.sv.gnu.org:9418
            github.com:443
            go.dev:443
            https.git.savannah.gnu.org:443
            motd.ubuntu.com:443
            objects.githubusercontent.com:443
            packages.microsoft.com:443
            packages.wolfi.dev:443
            ppa.launchpadcontent.net:443
            proxy.golang.org:443
            pypi.org:443
            raw.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443
            translationproject.org:443

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "./go.mod"

      - name: Integration and Unit Tests
        run: make integration
